#!/bin/bash
# Updates landing page with latest release info
# Usage: ./update_landing_page.sh <version>
# Example: ./update_landing_page.sh 2.8.2

set -e

VERSION="$1"
if [ -z "$VERSION" ]; then
    echo "❌ Usage: $0 <version>"
    echo "Example: $0 2.8.2"
    exit 1
fi

REPO_OWNER="ai-fresh"
REPO_NAME="ccgate"
REPO="${REPO_OWNER}/${REPO_NAME}"
PKG_URL="https://github.com/${REPO}/releases/download/v${VERSION}/CC.Gate-${VERSION}.pkg"
DMG_URL="https://github.com/${REPO}/releases/download/v${VERSION}/CC.Gate-${VERSION}.dmg"

echo "🔄 Updating landing page for v${VERSION}..."

# Update JSON-LD structured data
sed -i '' "s|\"downloadUrl\": \"[^\"]*\"|\"downloadUrl\": \"${PKG_URL}\"|g" index.html
sed -i '' "s|\"softwareVersion\": \"[^\"]*\"|\"softwareVersion\": \"${VERSION}\"|g" index.html

# Update all download links containing .pkg
sed -i '' "s|releases/download/v[0-9.]*/.*.pkg|releases/download/v${VERSION}/CC.Gate-${VERSION}.pkg|g" index.html

# Update all download links containing .dmg
sed -i '' "s|releases/download/v[0-9.]*/.*.dmg|releases/download/v${VERSION}/CC.Gate-${VERSION}.dmg|g" index.html

# Update version displays (if any inline text)
sed -i '' "s/version [0-9.]*</version ${VERSION}</g" index.html

git add index.html
git commit -m "chore: update landing page to v${VERSION}

- Updated download links to point to v${VERSION} release assets
- Updated structured data with latest version

Auto-generated by update_landing_page.sh"

git push origin main

echo "✅ Landing page updated to v${VERSION}"
echo "🌐 View at: https://${REPO_OWNER}.github.io/${REPO_NAME}/"
